name: flutter_firebase_ecommerce_app
description: An Ecommerce Flutter App with Firebase as Backend and Razopypay integration for payments.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.17
  cloud_functions: ^3.2.16
  colorful_safe_area: ^0.3.0
  dio: ^4.0.4
  double_back_to_close_app: ^2.1.0
  dynamic_height_grid_view: ^0.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_remix: ^0.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.3.0
  page_transition: ^2.0.9
  preload_page_view: ^0.1.6
  provider: ^6.0.2
  razorpay_flutter: ^1.3.0
  skeletons: ^0.0.3
  smooth_page_indicator: ^1.0.0+2
  splash_screen_view: ^3.0.0
  swipeable_page_route: ^0.2.6
  tap_debouncer: ^2.0.2
  uuid: ^3.0.6
  validators: ^3.0.0

splash_screen_view:
  color: "#ffffff"
  image: assets/logo.png
  color_dark: "#222222"
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie_files/
    - .env.local

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
