name: flutter_firebase_ecommerce_app
description: An Ecommerce Flutter App with Firebase as Backend and Razopypay
  integration for payments.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.3.0
  colorful_safe_area: ^0.3.0
  country_calling_code_picker: ^2.0.1
  dio: ^4.0.4
  dynamic_height_grid_view: ^0.0.3
  email_auth: ^1.0.0
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_remix: ^0.0.3
  flutter_speech: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  jiffy: ^5.0.0
  oktoast: ^3.2.0
  onesignal_flutter: ^3.3.2
  permission_handler: ^10.0.0
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  razorpay_flutter: ^1.3.0
  skeletons: ^0.0.3
  smooth_page_indicator: ^1.0.0+2
  splash_screen_view: ^3.0.0
  swipeable_page_route: ^0.2.6
  tap_debouncer: ^2.0.2
  uuid: ^3.0.6
  validators: ^3.0.0

splash_screen_view:
  color: "#ffffff"
  image: assets/logo_outline.png
  color_dark: "#222222"
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  android: true
  ios: true

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env.local

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
